# Generated by Django 4.2.5 on 2023-11-16 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('description', models.TextField()),
                ('adoption_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_name', models.CharField(max_length=255)),
                ('contact_information', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact_information', message='Contact information must be 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('adoption_date', models.DateField(auto_now_add=True)),
                ('pet_adopted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoptions.pet')),
            ],
        ),
    ]
