# Generated by Django 4.2.5 on 2023-11-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='donated',
            field=models.BooleanField(default=False),
        ),
    ]
