# Generated by Django 4.2.5 on 2023-11-25 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoptions', '0004_blogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1, verbose_name='Gender')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pet_images/', verbose_name='Pet Image')),
                ('donater_name', models.CharField(max_length=25)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact information must be a 10-digit number.', regex='^[0-9]{10}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
